<?xml version="1.0" encoding="utf-8"?><Database Name="SuruTest" Class="DbLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=bjwork95.cjng4ulqqzae.ap-northeast-1.rds.amazonaws.com;Initial Catalog=SuruTest;Persist Security Info=True;User ID=BJwork" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SuruTestConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.bjuser" Member="bjuser">
    <Type Name="bjuser">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="u_photo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="u_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="u_password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="u_email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="u_birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="u_gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="bjuser_personal_sport_menu" Member="personal_sport_menu" ThisKey="user_id" OtherKey="user_id" Type="personal_sport_menu" />
    </Type>
  </Table>
  <Table Name="dbo.personal_sport_menu" Member="personal_sport_menu">
    <Type Name="personal_sport_menu">
      <Column Name="p_menu_num" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="spdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SportID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="distance" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="reps" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sets" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="times" Type="System.TimeSpan" DbType="Time" CanBeNull="true" />
      <Column Name="finish" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="bjuser_personal_sport_menu" Member="bjuser" ThisKey="user_id" OtherKey="user_id" Type="bjuser" IsForeignKey="true" />
    </Type>
  </Table>
</Database>