#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestVersion3
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SuruTest")]
	public partial class dbLinqtoSqlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void Insertbjuser(bjuser instance);
    partial void Updatebjuser(bjuser instance);
    partial void Deletebjuser(bjuser instance);
    #endregion
		
		public dbLinqtoSqlDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SuruTestConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbLinqtoSqlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLinqtoSqlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLinqtoSqlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbLinqtoSqlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bjuser> bjuser
		{
			get
			{
				return this.GetTable<bjuser>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bjuser")]
	public partial class bjuser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _u_photo;
		
		private string _u_name;
		
		private string _u_password;
		
		private string _u_email;
		
		private System.Nullable<System.DateTime> _u_birth;
		
		private System.Nullable<bool> _u_gender;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onu_photoChanging(string value);
    partial void Onu_photoChanged();
    partial void Onu_nameChanging(string value);
    partial void Onu_nameChanged();
    partial void Onu_passwordChanging(string value);
    partial void Onu_passwordChanged();
    partial void Onu_emailChanging(string value);
    partial void Onu_emailChanged();
    partial void Onu_birthChanging(System.Nullable<System.DateTime> value);
    partial void Onu_birthChanged();
    partial void Onu_genderChanging(System.Nullable<bool> value);
    partial void Onu_genderChanged();
    #endregion
		
		public bjuser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_photo", DbType="NVarChar(MAX)")]
		public string u_photo
		{
			get
			{
				return this._u_photo;
			}
			set
			{
				if ((this._u_photo != value))
				{
					this.Onu_photoChanging(value);
					this.SendPropertyChanging();
					this._u_photo = value;
					this.SendPropertyChanged("u_photo");
					this.Onu_photoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_name", DbType="NVarChar(50)")]
		public string u_name
		{
			get
			{
				return this._u_name;
			}
			set
			{
				if ((this._u_name != value))
				{
					this.Onu_nameChanging(value);
					this.SendPropertyChanging();
					this._u_name = value;
					this.SendPropertyChanged("u_name");
					this.Onu_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_password", DbType="NVarChar(50)")]
		public string u_password
		{
			get
			{
				return this._u_password;
			}
			set
			{
				if ((this._u_password != value))
				{
					this.Onu_passwordChanging(value);
					this.SendPropertyChanging();
					this._u_password = value;
					this.SendPropertyChanged("u_password");
					this.Onu_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_email", DbType="NVarChar(50)")]
		public string u_email
		{
			get
			{
				return this._u_email;
			}
			set
			{
				if ((this._u_email != value))
				{
					this.Onu_emailChanging(value);
					this.SendPropertyChanging();
					this._u_email = value;
					this.SendPropertyChanged("u_email");
					this.Onu_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_birth", DbType="Date")]
		public System.Nullable<System.DateTime> u_birth
		{
			get
			{
				return this._u_birth;
			}
			set
			{
				if ((this._u_birth != value))
				{
					this.Onu_birthChanging(value);
					this.SendPropertyChanging();
					this._u_birth = value;
					this.SendPropertyChanged("u_birth");
					this.Onu_birthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_u_gender", DbType="Bit")]
		public System.Nullable<bool> u_gender
		{
			get
			{
				return this._u_gender;
			}
			set
			{
				if ((this._u_gender != value))
				{
					this.Onu_genderChanging(value);
					this.SendPropertyChanging();
					this._u_gender = value;
					this.SendPropertyChanged("u_gender");
					this.Onu_genderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
